using System.Text.Json;
using System.Text.Json.Serialization;
using SportowyHub.Models.Api;

namespace SportowyHub.Services.Api;

[JsonSourceGenerationOptions(
    PropertyNameCaseInsensitive = true,
    PropertyNamingPolicy = JsonKnownNamingPolicy.SnakeCaseLower)]
[JsonSerializable(typeof(LoginRequest))]
[JsonSerializable(typeof(LoginResponse))]
[JsonSerializable(typeof(LoginUser))]
[JsonSerializable(typeof(RegisterRequest))]
[JsonSerializable(typeof(RegisterResponse))]
[JsonSerializable(typeof(ApiError))]
[JsonSerializable(typeof(UserInfo))]
[JsonSerializable(typeof(ResendVerificationRequest))]
[JsonSerializable(typeof(ResendVerificationResponse))]
[JsonSerializable(typeof(UserProfile))]
[JsonSerializable(typeof(UserAccount))]
[JsonSerializable(typeof(OauthLinked))]
[JsonSerializable(typeof(UpdateProfileRequest))]
[JsonSerializable(typeof(UpdateProfileAccountRequest))]
[JsonSerializable(typeof(UpdateProfileResponse))]
[JsonSerializable(typeof(ListingSummary))]
[JsonSerializable(typeof(ListingsResponse))]
[JsonSerializable(typeof(ListingDetail))]
[JsonSerializable(typeof(SearchResultItem))]
[JsonSerializable(typeof(GeoLocation))]
[JsonSerializable(typeof(SearchAttribute))]
[JsonSerializable(typeof(SearchResponse))]
[JsonSerializable(typeof(FavoriteItem))]
[JsonSerializable(typeof(FavoritesIdsResponse))]
[JsonSerializable(typeof(FavoritesListResponse))]
[JsonSerializable(typeof(FavoriteActionResponse))]
[JsonSerializable(typeof(OAuthLoginRequest))]
[JsonSerializable(typeof(AvatarResponse))]
[JsonSerializable(typeof(Section))]
[JsonSerializable(typeof(SectionsResponse))]
[JsonSerializable(typeof(Category))]
[JsonSerializable(typeof(CategoriesResponse))]
[JsonSerializable(typeof(LocaleInfo))]
[JsonSerializable(typeof(PhoneVerificationRequestRequest))]
[JsonSerializable(typeof(PhoneVerificationRequestResponse))]
[JsonSerializable(typeof(PhoneVerificationVerifyRequest))]
[JsonSerializable(typeof(PhoneVerificationResult))]
[JsonSerializable(typeof(ThemePreferences))]
[JsonSerializable(typeof(CreateListingRequest))]
[JsonSerializable(typeof(UpdateListingRequest))]
[JsonSerializable(typeof(UpdateListingResponse))]
[JsonSerializable(typeof(UpdateStatusRequest))]
[JsonSerializable(typeof(UpdateStatusResponse))]
[JsonSerializable(typeof(ResubmitResponse))]
[JsonSerializable(typeof(MyListingSummary))]
[JsonSerializable(typeof(MyListingsResponse))]
[JsonSerializable(typeof(MediaItem))]
[JsonSerializable(typeof(MediaUrls))]
[JsonSerializable(typeof(Conversation))]
[JsonSerializable(typeof(ConversationsResponse))]
[JsonSerializable(typeof(Message))]
[JsonSerializable(typeof(MessagesResponse))]
[JsonSerializable(typeof(CreateConversationRequest))]
[JsonSerializable(typeof(SendMessageRequest))]
[JsonSerializable(typeof(ReportListingRequest))]
[JsonSerializable(typeof(ReportResponse))]
[JsonSerializable(typeof(DsarRequestItem))]
[JsonSerializable(typeof(DsarListResponse))]
[JsonSerializable(typeof(DsarRequestResponse))]
[JsonSerializable(typeof(Dictionary<string, string>))]
[JsonSerializable(typeof(List<string>))]
public partial class SportowyHubJsonContext : JsonSerializerContext;
