//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace SportowyHub.Resources.Strings;

using System.Globalization;
using System.Resources;

public static class AppResources
{
    private static ResourceManager? _resourceManager;

    public static ResourceManager ResourceManager =>
        _resourceManager ??= new ResourceManager(
            "SportowyHub.Resources.Strings.AppResources",
            typeof(AppResources).Assembly);

    public static CultureInfo? Culture { get; set; }

    // Tab labels
    public static string TabHome => ResourceManager.GetString("TabHome", Culture)!;
    public static string TabSearch => ResourceManager.GetString("TabSearch", Culture)!;
    public static string TabFavorites => ResourceManager.GetString("TabFavorites", Culture)!;
    public static string TabProfile => ResourceManager.GetString("TabProfile", Culture)!;

    // Auth
    public static string AuthSignIn => ResourceManager.GetString("AuthSignIn", Culture)!;
    public static string AuthEmail => ResourceManager.GetString("AuthEmail", Culture)!;
    public static string AuthPassword => ResourceManager.GetString("AuthPassword", Culture)!;
    public static string AuthEnterEmail => ResourceManager.GetString("AuthEnterEmail", Culture)!;
    public static string AuthEnterPassword => ResourceManager.GetString("AuthEnterPassword", Culture)!;
    public static string AuthForgotPassword => ResourceManager.GetString("AuthForgotPassword", Culture)!;
    public static string AuthLogin => ResourceManager.GetString("AuthLogin", Culture)!;
    public static string AuthNoAccount => ResourceManager.GetString("AuthNoAccount", Culture)!;
    public static string AuthCreateAccount => ResourceManager.GetString("AuthCreateAccount", Culture)!;
    public static string AuthConfirmPassword => ResourceManager.GetString("AuthConfirmPassword", Culture)!;
    public static string AuthConfirmYourPassword => ResourceManager.GetString("AuthConfirmYourPassword", Culture)!;
    public static string AuthInvalidEmail => ResourceManager.GetString("AuthInvalidEmail", Culture)!;
    public static string AuthPasswordsDoNotMatch => ResourceManager.GetString("AuthPasswordsDoNotMatch", Culture)!;
    public static string AuthPhone => ResourceManager.GetString("AuthPhone", Culture)!;
    public static string AuthEnterPhone => ResourceManager.GetString("AuthEnterPhone", Culture)!;

    // Registration Success
    public static string AuthRegistrationSuccess => ResourceManager.GetString("AuthRegistrationSuccess", Culture)!;
    public static string AuthRegistrationSuccessMessage => ResourceManager.GetString("AuthRegistrationSuccessMessage", Culture)!;

    // Email Verification
    public static string EmailVerificationTitle => ResourceManager.GetString("EmailVerificationTitle", Culture)!;
    public static string EmailVerificationDescription => ResourceManager.GetString("EmailVerificationDescription", Culture)!;
    public static string EmailVerificationResend => ResourceManager.GetString("EmailVerificationResend", Culture)!;
    public static string EmailVerificationResent => ResourceManager.GetString("EmailVerificationResent", Culture)!;
    public static string EmailVerificationBackToLogin => ResourceManager.GetString("EmailVerificationBackToLogin", Culture)!;
    public static string EmailVerificationError => ResourceManager.GetString("EmailVerificationError", Culture)!;

    // Password strength
    public static string PasswordStrengthStrong => ResourceManager.GetString("PasswordStrengthStrong", Culture)!;
    public static string PasswordStrengthMedium => ResourceManager.GetString("PasswordStrengthMedium", Culture)!;
    public static string PasswordStrengthWeak => ResourceManager.GetString("PasswordStrengthWeak", Culture)!;

    // Home
    public static string HomeTitle => ResourceManager.GetString("HomeTitle", Culture)!;
    public static string HomeContentComingSoon => ResourceManager.GetString("HomeContentComingSoon", Culture)!;

    // Search
    public static string SearchPlaceholder => ResourceManager.GetString("SearchPlaceholder", Culture)!;
    public static string SearchRecentSearches => ResourceManager.GetString("SearchRecentSearches", Culture)!;
    public static string SearchPopularSearches => ResourceManager.GetString("SearchPopularSearches", Culture)!;
    public static string SearchClearRecent => ResourceManager.GetString("SearchClearRecent", Culture)!;

    // Favorites
    public static string FavoritesTitle => ResourceManager.GetString("FavoritesTitle", Culture)!;
    public static string FavoritesEmpty => ResourceManager.GetString("FavoritesEmpty", Culture)!;
    public static string FavoritesSignInPrompt => ResourceManager.GetString("FavoritesSignInPrompt", Culture)!;
    public static string FavoritesSignIn => ResourceManager.GetString("FavoritesSignIn", Culture)!;

    // Profile
    public static string ProfileWelcome => ResourceManager.GetString("ProfileWelcome", Culture)!;
    public static string ProfileCreateAccount => ResourceManager.GetString("ProfileCreateAccount", Culture)!;
    public static string ProfileAccountProfile => ResourceManager.GetString("ProfileAccountProfile", Culture)!;
    public static string ProfileSignIn => ResourceManager.GetString("ProfileSignIn", Culture)!;
    public static string ProfileAccountSection => ResourceManager.GetString("ProfileAccountSection", Culture)!;
    public static string ProfileSettingsSection => ResourceManager.GetString("ProfileSettingsSection", Culture)!;

    // Settings
    public static string SettingsLanguage => ResourceManager.GetString("SettingsLanguage", Culture)!;
    public static string SettingsTheme => ResourceManager.GetString("SettingsTheme", Culture)!;
    public static string SettingsThemeLight => ResourceManager.GetString("SettingsThemeLight", Culture)!;
    public static string SettingsThemeDark => ResourceManager.GetString("SettingsThemeDark", Culture)!;
    public static string SettingsThemeSystem => ResourceManager.GetString("SettingsThemeSystem", Culture)!;
    public static string SettingsLanguageSystem => ResourceManager.GetString("SettingsLanguageSystem", Culture)!;
    public static string SettingsLanguagePl => ResourceManager.GetString("SettingsLanguagePl", Culture)!;
    public static string SettingsLanguageEn => ResourceManager.GetString("SettingsLanguageEn", Culture)!;
    public static string SettingsLanguageUk => ResourceManager.GetString("SettingsLanguageUk", Culture)!;
    public static string SettingsLanguageRu => ResourceManager.GetString("SettingsLanguageRu", Culture)!;

    // Sign Out
    public static string SignOut => ResourceManager.GetString("SignOut", Culture)!;
    public static string SignOutConfirmTitle => ResourceManager.GetString("SignOutConfirmTitle", Culture)!;
    public static string SignOutConfirmMessage => ResourceManager.GetString("SignOutConfirmMessage", Culture)!;
    public static string Cancel => ResourceManager.GetString("Cancel", Culture)!;

    // Account Profile
    public static string ProfileContact => ResourceManager.GetString("ProfileContact", Culture)!;
    public static string ProfileEmail => ResourceManager.GetString("ProfileEmail", Culture)!;
    public static string ProfilePhone => ResourceManager.GetString("ProfilePhone", Culture)!;
    public static string ProfileAccount => ResourceManager.GetString("ProfileAccount", Culture)!;
    public static string ProfileVerified => ResourceManager.GetString("ProfileVerified", Culture)!;
    public static string ProfileNotVerified => ResourceManager.GetString("ProfileNotVerified", Culture)!;
    public static string ProfileNotSet => ResourceManager.GetString("ProfileNotSet", Culture)!;
    public static string ProfileTrustLevel => ResourceManager.GetString("ProfileTrustLevel", Culture)!;
    public static string ProfileLoadError => ResourceManager.GetString("ProfileLoadError", Culture)!;
    public static string ProfileReputationScore => ResourceManager.GetString("ProfileReputationScore", Culture)!;
    public static string ProfileBalance => ResourceManager.GetString("ProfileBalance", Culture)!;
    public static string ProfileGoogleLinked => ResourceManager.GetString("ProfileGoogleLinked", Culture)!;
    public static string ProfileLinked => ResourceManager.GetString("ProfileLinked", Culture)!;
    public static string ProfileNotLinked => ResourceManager.GetString("ProfileNotLinked", Culture)!;

    // Edit Profile
    public static string EditProfileTitle => ResourceManager.GetString("EditProfileTitle", Culture)!;
    public static string EditProfileFirstName => ResourceManager.GetString("EditProfileFirstName", Culture)!;
    public static string EditProfileLastName => ResourceManager.GetString("EditProfileLastName", Culture)!;
    public static string EditProfilePhone => ResourceManager.GetString("EditProfilePhone", Culture)!;
    public static string EditProfileNotifications => ResourceManager.GetString("EditProfileNotifications", Culture)!;
    public static string EditProfileQuietHoursStart => ResourceManager.GetString("EditProfileQuietHoursStart", Culture)!;
    public static string EditProfileQuietHoursEnd => ResourceManager.GetString("EditProfileQuietHoursEnd", Culture)!;
    public static string EditProfileSave => ResourceManager.GetString("EditProfileSave", Culture)!;
    public static string EditProfileSuccess => ResourceManager.GetString("EditProfileSuccess", Culture)!;
    public static string EditProfileError => ResourceManager.GetString("EditProfileError", Culture)!;
    public static string EditProfileInvalidTime => ResourceManager.GetString("EditProfileInvalidTime", Culture)!;

    // Home Feed
    public static string HomeEmptyListings => ResourceManager.GetString("HomeEmptyListings", Culture)!;

    // Errors
    public static string ErrorGeneric => ResourceManager.GetString("ErrorGeneric", Culture)!;

    // Search Results
    public static string SearchNoResults => ResourceManager.GetString("SearchNoResults", Culture)!;

    // My Listings
    public static string ProfileMyListings => ResourceManager.GetString("ProfileMyListings", Culture)!;
    public static string MyListingsTitle => ResourceManager.GetString("MyListingsTitle", Culture)!;
    public static string MyListingsFilterAll => ResourceManager.GetString("MyListingsFilterAll", Culture)!;
    public static string MyListingsFilterDraft => ResourceManager.GetString("MyListingsFilterDraft", Culture)!;
    public static string MyListingsFilterPublished => ResourceManager.GetString("MyListingsFilterPublished", Culture)!;
    public static string MyListingsFilterPending => ResourceManager.GetString("MyListingsFilterPending", Culture)!;
    public static string MyListingsFilterRejected => ResourceManager.GetString("MyListingsFilterRejected", Culture)!;
    public static string MyListingsFilterHidden => ResourceManager.GetString("MyListingsFilterHidden", Culture)!;
    public static string MyListingsEmpty => ResourceManager.GetString("MyListingsEmpty", Culture)!;
    public static string MyListingsEmptyCreate => ResourceManager.GetString("MyListingsEmptyCreate", Culture)!;
    public static string MyListingsPublish => ResourceManager.GetString("MyListingsPublish", Culture)!;
    public static string MyListingsHide => ResourceManager.GetString("MyListingsHide", Culture)!;
    public static string MyListingsResubmit => ResourceManager.GetString("MyListingsResubmit", Culture)!;
    public static string MyListingsDelete => ResourceManager.GetString("MyListingsDelete", Culture)!;
    public static string MyListingsDeleteConfirmTitle => ResourceManager.GetString("MyListingsDeleteConfirmTitle", Culture)!;
    public static string MyListingsDeleteConfirmMessage => ResourceManager.GetString("MyListingsDeleteConfirmMessage", Culture)!;
    public static string MyListingsStatusDraft => ResourceManager.GetString("MyListingsStatusDraft", Culture)!;
    public static string MyListingsStatusPublished => ResourceManager.GetString("MyListingsStatusPublished", Culture)!;
    public static string MyListingsStatusPending => ResourceManager.GetString("MyListingsStatusPending", Culture)!;
    public static string MyListingsStatusRejected => ResourceManager.GetString("MyListingsStatusRejected", Culture)!;
    public static string MyListingsStatusHidden => ResourceManager.GetString("MyListingsStatusHidden", Culture)!;

    // Create/Edit Listing
    public static string CreateListingTitle => ResourceManager.GetString("CreateListingTitle", Culture)!;
    public static string EditListingTitle => ResourceManager.GetString("EditListingTitle", Culture)!;
    public static string ListingFieldCategory => ResourceManager.GetString("ListingFieldCategory", Culture)!;
    public static string ListingFieldSection => ResourceManager.GetString("ListingFieldSection", Culture)!;
    public static string ListingFieldTitle => ResourceManager.GetString("ListingFieldTitle", Culture)!;
    public static string ListingFieldDescription => ResourceManager.GetString("ListingFieldDescription", Culture)!;
    public static string ListingFieldPrice => ResourceManager.GetString("ListingFieldPrice", Culture)!;
    public static string ListingFieldCurrency => ResourceManager.GetString("ListingFieldCurrency", Culture)!;
    public static string ListingFieldCityId => ResourceManager.GetString("ListingFieldCityId", Culture)!;
    public static string ListingFieldVoivodeshipId => ResourceManager.GetString("ListingFieldVoivodeshipId", Culture)!;
    public static string ListingFieldLocale => ResourceManager.GetString("ListingFieldLocale", Culture)!;
    public static string ListingPhotosTitle => ResourceManager.GetString("ListingPhotosTitle", Culture)!;
    public static string ListingAddPhoto => ResourceManager.GetString("ListingAddPhoto", Culture)!;
    public static string ListingSave => ResourceManager.GetString("ListingSave", Culture)!;
    public static string ListingCreateSuccess => ResourceManager.GetString("ListingCreateSuccess", Culture)!;
    public static string ListingEditSuccess => ResourceManager.GetString("ListingEditSuccess", Culture)!;
    public static string ListingTitleRequired => ResourceManager.GetString("ListingTitleRequired", Culture)!;
    public static string ListingCategoryRequired => ResourceManager.GetString("ListingCategoryRequired", Culture)!;
}
