//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace SportowyHub.Resources.Strings;

using System.Globalization;
using System.Resources;

public static class AppResources
{
    private static ResourceManager? _resourceManager;

    public static ResourceManager ResourceManager =>
        _resourceManager ??= new ResourceManager(
            "SportowyHub.Resources.Strings.AppResources",
            typeof(AppResources).Assembly);

    public static CultureInfo? Culture { get; set; }

    // Tab labels
    public static string TabHome => ResourceManager.GetString("TabHome", Culture)!;
    public static string TabSearch => ResourceManager.GetString("TabSearch", Culture)!;
    public static string TabFavorites => ResourceManager.GetString("TabFavorites", Culture)!;
    public static string TabProfile => ResourceManager.GetString("TabProfile", Culture)!;

    // Auth
    public static string AuthSignIn => ResourceManager.GetString("AuthSignIn", Culture)!;
    public static string AuthEmail => ResourceManager.GetString("AuthEmail", Culture)!;
    public static string AuthPassword => ResourceManager.GetString("AuthPassword", Culture)!;
    public static string AuthEnterEmail => ResourceManager.GetString("AuthEnterEmail", Culture)!;
    public static string AuthEnterPassword => ResourceManager.GetString("AuthEnterPassword", Culture)!;
    public static string AuthForgotPassword => ResourceManager.GetString("AuthForgotPassword", Culture)!;
    public static string AuthLogin => ResourceManager.GetString("AuthLogin", Culture)!;
    public static string AuthNoAccount => ResourceManager.GetString("AuthNoAccount", Culture)!;
    public static string AuthCreateAccount => ResourceManager.GetString("AuthCreateAccount", Culture)!;
    public static string AuthConfirmPassword => ResourceManager.GetString("AuthConfirmPassword", Culture)!;
    public static string AuthConfirmYourPassword => ResourceManager.GetString("AuthConfirmYourPassword", Culture)!;
    public static string AuthInvalidEmail => ResourceManager.GetString("AuthInvalidEmail", Culture)!;
    public static string AuthPasswordsDoNotMatch => ResourceManager.GetString("AuthPasswordsDoNotMatch", Culture)!;
    public static string AuthPhone => ResourceManager.GetString("AuthPhone", Culture)!;
    public static string AuthEnterPhone => ResourceManager.GetString("AuthEnterPhone", Culture)!;

    // Registration Success
    public static string AuthRegistrationSuccess => ResourceManager.GetString("AuthRegistrationSuccess", Culture)!;
    public static string AuthRegistrationSuccessMessage => ResourceManager.GetString("AuthRegistrationSuccessMessage", Culture)!;

    // Email Verification
    public static string EmailVerificationTitle => ResourceManager.GetString("EmailVerificationTitle", Culture)!;
    public static string EmailVerificationDescription => ResourceManager.GetString("EmailVerificationDescription", Culture)!;
    public static string EmailVerificationResend => ResourceManager.GetString("EmailVerificationResend", Culture)!;
    public static string EmailVerificationResent => ResourceManager.GetString("EmailVerificationResent", Culture)!;
    public static string EmailVerificationBackToLogin => ResourceManager.GetString("EmailVerificationBackToLogin", Culture)!;
    public static string EmailVerificationError => ResourceManager.GetString("EmailVerificationError", Culture)!;

    // Password strength
    public static string PasswordStrengthStrong => ResourceManager.GetString("PasswordStrengthStrong", Culture)!;
    public static string PasswordStrengthMedium => ResourceManager.GetString("PasswordStrengthMedium", Culture)!;
    public static string PasswordStrengthWeak => ResourceManager.GetString("PasswordStrengthWeak", Culture)!;

    // Home
    public static string HomeTitle => ResourceManager.GetString("HomeTitle", Culture)!;
    public static string HomeContentComingSoon => ResourceManager.GetString("HomeContentComingSoon", Culture)!;

    // Search
    public static string SearchPlaceholder => ResourceManager.GetString("SearchPlaceholder", Culture)!;
    public static string SearchRecentSearches => ResourceManager.GetString("SearchRecentSearches", Culture)!;
    public static string SearchPopularSearches => ResourceManager.GetString("SearchPopularSearches", Culture)!;

    // Favorites
    public static string FavoritesTitle => ResourceManager.GetString("FavoritesTitle", Culture)!;

    // Profile
    public static string ProfileWelcome => ResourceManager.GetString("ProfileWelcome", Culture)!;
    public static string ProfileCreateAccount => ResourceManager.GetString("ProfileCreateAccount", Culture)!;
    public static string ProfileAccountProfile => ResourceManager.GetString("ProfileAccountProfile", Culture)!;
    public static string ProfileSignIn => ResourceManager.GetString("ProfileSignIn", Culture)!;
    public static string ProfileAccountSection => ResourceManager.GetString("ProfileAccountSection", Culture)!;
    public static string ProfileSettingsSection => ResourceManager.GetString("ProfileSettingsSection", Culture)!;

    // Settings
    public static string SettingsLanguage => ResourceManager.GetString("SettingsLanguage", Culture)!;
    public static string SettingsTheme => ResourceManager.GetString("SettingsTheme", Culture)!;
    public static string SettingsThemeLight => ResourceManager.GetString("SettingsThemeLight", Culture)!;
    public static string SettingsThemeDark => ResourceManager.GetString("SettingsThemeDark", Culture)!;
    public static string SettingsThemeSystem => ResourceManager.GetString("SettingsThemeSystem", Culture)!;
    public static string SettingsLanguageSystem => ResourceManager.GetString("SettingsLanguageSystem", Culture)!;
    public static string SettingsLanguagePl => ResourceManager.GetString("SettingsLanguagePl", Culture)!;
    public static string SettingsLanguageEn => ResourceManager.GetString("SettingsLanguageEn", Culture)!;
    public static string SettingsLanguageUk => ResourceManager.GetString("SettingsLanguageUk", Culture)!;
    public static string SettingsLanguageRu => ResourceManager.GetString("SettingsLanguageRu", Culture)!;

    // Sign Out
    public static string SignOut => ResourceManager.GetString("SignOut", Culture)!;
    public static string SignOutConfirmTitle => ResourceManager.GetString("SignOutConfirmTitle", Culture)!;
    public static string SignOutConfirmMessage => ResourceManager.GetString("SignOutConfirmMessage", Culture)!;
    public static string Cancel => ResourceManager.GetString("Cancel", Culture)!;
}
